lib = File.dirname(__FILE__)
require File.join(lib, "istat", "utils")
require File.join(lib, "istat", "frames", "base")
require File.join(lib, "istat", "frames", "authentication")
require File.join(lib, "istat", "frames", "connection_test")
require File.join(lib, "istat", "frames", "register")
require File.join(lib, "istat", "frames", "measurement")
require File.join(lib, "istat", "client")
require File.join(lib, "istat", "version")
